/*
    SPDX-FileCopyrightText: 2026 Ark Royal <awright42mk1@protonmail.com>

    SPDX-License-Identifier: GPL-2.0-or-later
*/

#pragma once

#include "kwin_export.h"

#include <QRect>
#include <QSize>

#include <cstdint>
#include <map>
#include <memory>
#include <unordered_map>
#include <vector>
#include <vulkan/vulkan.h>

struct VmaAllocation_T;
typedef VmaAllocation_T *VmaAllocation;

namespace KWin
{

class VulkanContext;

/**
 * @brief Shared mipmapped image for window-thumbnail texturing under the
 * Vulkan compositor.
 *
 * Window thumbnails (`WindowThumbnailSource`) used to render into a
 * per-source offscreen framebuffer and read the result back to a QImage
 * for Qt to upload as a fresh QSGTexture each frame. With Qt Quick now on
 * the Vulkan RHI under this compositor, that GPU→CPU→GPU roundtrip is
 * unnecessary; we can render into a Vulkan image and let Qt sample it
 * directly via a `QSGRenderNode`.
 *
 * The atlas packs many source-window thumbnails into one
 * `4096 × 4096 RGBA8_SRGB` image with 5 mip levels. Each thumbnail is a
 * sub-rect at mip 0; the remaining mip levels are generated by
 * `vkCmdBlitImage` cascades restricted to the slot's sub-rect.
 * `KWIN_THUMBNAIL_PAD_PX` (16) pixels of padding around each slot
 * prevent texel bleed between neighbours at the highest mip levels.
 *
 * Atlas overflow (no shelf has room) falls back to a per-slot dedicated
 * mipmapped image — same `Slot` API, consumers don't care which kind
 * they got.
 *
 * Lifetime: process-singleton, created lazily on first reserve, tied to
 * the `VulkanContext`. Released slots return their atlas rects to a
 * size-bucketed free list for reuse; no defragmentation pass.
 */
class KWIN_EXPORT VulkanThumbnailAtlas
{
public:
    /**
     * @brief A reservation within the atlas, or a dedicated per-source image
     * when the atlas overflows. Same field layout in both cases; consumers
     * sample `srgbView` with the atlas sampler restricted by `rect`.
     */
    struct Slot
    {
        /// Rect of mip 0 storage that the consumer should render into.
        /// For atlas-resident slots this is the sub-rect inside the
        /// 4096² atlas. For fallback slots it is `(0, 0, size)`.
        QRect rect;
        /// Number of valid mip levels (atlas: kMipLevels; fallback:
        /// computed from `rect` size).
        uint32_t mipLevels = 0;
        /// Image the consumer samples (atlas: shared atlas image;
        /// fallback: per-slot dedicated image).
        VkImage image = VK_NULL_HANDLE;
        /// Full-mip-range SRGB image view for sampling.
        VkImageView srgbView = VK_NULL_HANDLE;
        /// Mip-0-only view, used as the color attachment when the source
        /// window is rendered into the slot.
        VkImageView mipZeroView = VK_NULL_HANDLE;
        /// Identifies the entry in the atlas's internal allocator state
        /// (atlas slot record or fallback record); 0 means invalid.
        uint64_t handle = 0;
        /// True when this slot owns a dedicated fallback image.
        bool isFallback = false;
        /// True when the slot's mip storage has been touched at least
        /// once by a source render. Until then, the descriptor would
        /// sample garbage; consumers must skip drawing.
        bool hasContent = false;

        bool isValid() const
        {
            return handle != 0;
        }
    };

    /**
     * @brief Process-wide accessor. Creates the atlas image lazily on
     * first reserve. Returns `nullptr` only on hard initialization
     * failure (e.g., vmaCreateImage fails).
     */
    static VulkanThumbnailAtlas *get(VulkanContext *ctx);

    /**
     * @brief Tear down the atlas instance bound to @p ctx. Must be
     * called from VulkanContext's destructor *before* the device is
     * cleaned up — otherwise the atlas's static-storage destructor runs
     * during global teardown when the Vulkan device is already gone,
     * and the queued vkDestroyImageView calls crash with "Invalid
     * device" (VUID-vkDestroyImageView-device-parameter).
     */
    static void dropForContext(VulkanContext *ctx);

    /// Reserve a slot at least `requestedSize` (atlas adds padding
    /// internally). Returns an invalid Slot only if both the atlas and
    /// the fallback path failed to allocate.
    Slot reserve(QSize requestedSize);

    /// Release a slot. For atlas slots, returns the rect to the size-
    /// bucketed free list. For fallback slots, queues the owned image
    /// for deferred destruction.
    void release(Slot &slot);

    /// Record a layout transition: slot's mip 0 → COLOR_ATTACHMENT_OPTIMAL.
    /// Call before recording the source-render pass that writes into the
    /// slot.
    void prepareForRenderTo(VkCommandBuffer cmd, const Slot &slot);

    /// After the source render finishes, transition mip 0 to
    /// TRANSFER_SRC and the remaining mips to TRANSFER_DST. Then record
    /// the mip blit cascade and a final pipeline barrier publishing all
    /// mips as `SHADER_READ_ONLY_OPTIMAL` for `FRAGMENT_SHADER` reads.
    /// Caller submits the command buffer; same-queue ordering plus this
    /// barrier guarantees Qt's subsequent submit sees the data.
    void generateMipsAndPublish(VkCommandBuffer cmd, Slot &slot);

    /// Sampler suitable for thumbnail consumers: linear filter,
    /// `LINEAR_MIPMAP_LINEAR` mip mode, clamp-to-edge wrap.
    VkSampler sampler() const
    {
        return m_sampler;
    }

    /// SRGB image view of the shared atlas, lazily allocating the
    /// atlas image on first call. Use this when a consumer needs any
    /// valid view bound to the descriptor — e.g. the OverviewEffectV2
    /// desktop bar, whose shader doesn't actually sample but still
    /// requires a non-null binding. Returns VK_NULL_HANDLE only if
    /// atlas initialisation fails.
    VkImageView atlasView();

    /// Mip levels in any atlas-resident slot.
    static constexpr uint32_t kMipLevels = 5;
    /// Atlas dimensions (square).
    static constexpr int kAtlasSize = 4096;
    /// Padding pixels around each slot. Must be at least 2^(kMipLevels-1)
    /// to prevent neighbour bleed at the smallest mip level (16 covers
    /// mips 0-4 cleanly).
    static constexpr int kSlotPadding = 16;

    // The accessor is `get()` above; the ctor/dtor are public so the
    // process-singleton storage (`std::unique_ptr`) can manage lifetime.
    // Don't call them directly.
    explicit VulkanThumbnailAtlas(VulkanContext *ctx);
    ~VulkanThumbnailAtlas();
    VulkanThumbnailAtlas(const VulkanThumbnailAtlas &) = delete;
    VulkanThumbnailAtlas &operator=(const VulkanThumbnailAtlas &) = delete;

private:
    bool ensureAtlasInitialized();
    bool createAtlasImage();
    bool createSampler();
    bool createMipZeroView(VkImage image, VkImageView *out);
    bool createSrgbView(VkImage image, uint32_t mipLevels, VkImageView *out);
    bool allocateFallback(QSize size, Slot *outSlot);

    /// Shelf packer: try to place a `(paddedW × paddedH)` block.
    /// Returns the inner rect (without padding) on success; an empty
    /// rect if it doesn't fit any current shelf or a new one.
    QRect packIntoAtlas(QSize paddedSize);

    /// Free-list lookup: returns a freed rect of at least `requestedSize`
    /// (inner, without padding) if any.
    QRect findFreeRect(QSize requestedSize);

    VulkanContext *m_context;

    VkImage m_atlasImage = VK_NULL_HANDLE;
    VmaAllocation m_atlasAlloc = nullptr;
    VkImageView m_atlasSrgbView = VK_NULL_HANDLE;
    VkImageView m_atlasMipZeroView = VK_NULL_HANDLE;
    VkSampler m_sampler = VK_NULL_HANDLE;

    /// Whether the atlas image's mip levels have been transitioned out
    /// of `VK_IMAGE_LAYOUT_UNDEFINED` at least once. Tracked per-slot
    /// after that, via `Slot::hasContent`.
    bool m_atlasFirstUse = true;
    bool m_atlasReady = false;
    bool m_atlasFailed = false;

    /// Shelf-packer state: each shelf is a horizontal band of fixed
    /// height with a left-to-right cursor.
    struct Shelf
    {
        int y;
        int height;
        int cursorX;
    };
    std::vector<Shelf> m_shelves;
    int m_atlasUsedY = 0;

    /// Size-bucketed free list (key = max(w, h)). Best-fit lookup.
    std::multimap<int, QRect> m_freeRects;

    /// Tracked atlas slots so release() can locate the rect to free.
    std::unordered_map<uint64_t, QRect> m_atlasSlotRects;

    /// Tracked fallback slots so release() can queue their images for
    /// destruction.
    struct FallbackRecord
    {
        VkImage image;
        VmaAllocation allocation;
        VkImageView srgbView;
        VkImageView mipZeroView;
    };
    std::unordered_map<uint64_t, FallbackRecord> m_fallbackSlots;

    uint64_t m_nextHandle = 1;
};

} // namespace KWin
